/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Campamento;
import Threads.Monitor;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;

/**
 *
 * @author Francisco
 */
public class InterfazSistema extends javax.swing.JFrame {

    /**
     * Creates new form InterfazSistema
     */
    private int x, y;
    
    public InterfazSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentana = new javax.swing.JPanel();
        jPanelControlVentana = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelRunnear = new javax.swing.JPanel();
        jLabelMinimizar = new javax.swing.JLabel();
        jPanelEspaciado = new javax.swing.JPanel();
        jPanelMinimizar = new javax.swing.JPanel();
        jLabelMinimizar1 = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jPanelEntradaNorte = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelEntradaSur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelVentana.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentana.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jPanelControlVentana.setBackground(new java.awt.Color(39, 43, 51));
        jPanelControlVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelControlVentanaMouseDragged(evt);
            }
        });
        jPanelControlVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelControlVentanaMousePressed(evt);
            }
        });
        jPanelControlVentana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(39, 43, 51));
        jPanelCerrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setFont(new java.awt.Font("Roboto Light", 0, 28)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jPanelCerrar.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 15));

        jPanelControlVentana.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 5, 60, 25));

        jPanelRunnear.setBackground(new java.awt.Color(39, 43, 51));
        jPanelRunnear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelRunnear.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanelRunnear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRunnearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRunnearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRunnearMouseExited(evt);
            }
        });
        jPanelRunnear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMinimizar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabelMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar.setText("RUN");
        jPanelRunnear.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 25));

        jPanelControlVentana.add(jPanelRunnear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 60, 25));

        jPanelEspaciado.setBackground(new java.awt.Color(39, 43, 51));

        javax.swing.GroupLayout jPanelEspaciadoLayout = new javax.swing.GroupLayout(jPanelEspaciado);
        jPanelEspaciado.setLayout(jPanelEspaciadoLayout);
        jPanelEspaciadoLayout.setHorizontalGroup(
            jPanelEspaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanelEspaciadoLayout.setVerticalGroup(
            jPanelEspaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelControlVentana.add(jPanelEspaciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, 40));

        jPanelMinimizar.setBackground(new java.awt.Color(39, 43, 51));
        jPanelMinimizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelMinimizar.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseExited(evt);
            }
        });
        jPanelMinimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMinimizar1.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLabelMinimizar1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimizar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar1.setText("_");
        jPanelMinimizar.add(jLabelMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        jPanelControlVentana.add(jPanelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 5, 60, 25));

        jPanelDatos.setBackground(new java.awt.Color(0, 0, 0));
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEntradaNorte.setBackground(new java.awt.Color(39, 43, 51));
        jPanelEntradaNorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelEntradaNorte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTRADA NORTE");
        jPanelEntradaNorte.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 30));

        jPanelDatos.add(jPanelEntradaNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 260));

        jPanelEntradaSur.setBackground(new java.awt.Color(39, 43, 51));
        jPanelEntradaSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelEntradaSur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRADA SUR");
        jPanelEntradaSur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 30));

        jPanelDatos.add(jPanelEntradaSur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, 260));

        javax.swing.GroupLayout jPanelVentanaLayout = new javax.swing.GroupLayout(jPanelVentana);
        jPanelVentana.setLayout(jPanelVentanaLayout);
        jPanelVentanaLayout.setHorizontalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelControlVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelVentanaLayout.setVerticalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentanaLayout.createSequentialGroup()
                .addComponent(jPanelControlVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(255,106,105));
        jLabelCerrar.setForeground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(39,43,51));
        jLabelCerrar.setForeground( new Color(255,106,105));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelControlVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControlVentanaMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanelControlVentanaMousePressed

    private void jPanelControlVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControlVentanaMouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanelControlVentanaMouseDragged

    private void jPanelRunnearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRunnearMouseEntered
        // TODO add your handling code here:
        jPanelRunnear.setBackground( new Color(122,130,142));
    }//GEN-LAST:event_jPanelRunnearMouseEntered

    private void jPanelRunnearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRunnearMouseExited
        // TODO add your handling code here:
        jPanelRunnear.setBackground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelRunnearMouseExited

    private void jPanelRunnearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRunnearMouseClicked
        // TODO add your handling code here:
        
        
        
        Campamento CampamentoInfantil = new Campamento();
        
                for (int m = 1; m <= 4; m++)
                {
                    Monitor monitor = new Monitor(m);
                }
        
    }//GEN-LAST:event_jPanelRunnearMouseClicked

    private void jPanelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jPanelMinimizarMouseClicked

    private void jPanelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseEntered
        // TODO add your handling code here:
        jPanelMinimizar.setBackground( new Color(122,130,142));
    }//GEN-LAST:event_jPanelMinimizarMouseEntered

    private void jPanelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseExited
        // TODO add your handling code here:
        jPanelMinimizar.setBackground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelMinimizarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazSistema interfaz = new InterfazSistema();
                interfaz.setLocationRelativeTo(null);
                interfaz.setVisible(true);
                interfaz.x = interfaz.getX();
                interfaz.y = interfaz.getY();            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelMinimizar1;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelControlVentana;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelEntradaNorte;
    private javax.swing.JPanel jPanelEntradaSur;
    private javax.swing.JPanel jPanelEspaciado;
    private javax.swing.JPanel jPanelMinimizar;
    private javax.swing.JPanel jPanelRunnear;
    private javax.swing.JPanel jPanelVentana;
    // End of variables declaration//GEN-END:variables
}
