/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RMI;

import ClasesAsociadasJFrame.ListaNiños;
import ClasesAsociadasJFrame.ListaMonitores;
import ClasesAsociadasJFrame.Plazas;
import Actividades.Merienda;
import Actividades.Soga;
import Actividades.Tirolina;
import Actividades.ZonaComun;
import Clases.Campamento;
import Entradas.EntradaNorte;
import Entradas.EntradaSur;
import Threads.Monitor;
import Threads.Niño;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import static java.lang.Thread.sleep;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Francisco
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form InterfazSistema
     */
    private int x, y;
    
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentana = new javax.swing.JPanel();
        jPanelControlVentana = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelEspaciado = new javax.swing.JPanel();
        jPanelMinimizar = new javax.swing.JPanel();
        jLabelMinimizar = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jPanelActividades1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelActividades2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabelUsosTirolina = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabelColaEsperaTirolina = new javax.swing.JLabel();
        jLabelLupaUsosTirolina = new javax.swing.JLabel();
        jLabelLupaColaEsperaTirolina = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelVentana.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentana.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jPanelControlVentana.setBackground(new java.awt.Color(39, 43, 51));
        jPanelControlVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelControlVentanaMouseDragged(evt);
            }
        });
        jPanelControlVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelControlVentanaMousePressed(evt);
            }
        });
        jPanelControlVentana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(39, 43, 51));
        jPanelCerrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setFont(new java.awt.Font("Roboto Light", 0, 28)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jPanelCerrar.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 15));

        jPanelControlVentana.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 5, 60, 25));

        jPanelEspaciado.setBackground(new java.awt.Color(39, 43, 51));

        javax.swing.GroupLayout jPanelEspaciadoLayout = new javax.swing.GroupLayout(jPanelEspaciado);
        jPanelEspaciado.setLayout(jPanelEspaciadoLayout);
        jPanelEspaciadoLayout.setHorizontalGroup(
            jPanelEspaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanelEspaciadoLayout.setVerticalGroup(
            jPanelEspaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelControlVentana.add(jPanelEspaciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, 40));

        jPanelMinimizar.setBackground(new java.awt.Color(39, 43, 51));
        jPanelMinimizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelMinimizar.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseExited(evt);
            }
        });
        jPanelMinimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMinimizar.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLabelMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar.setText("_");
        jPanelMinimizar.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 25));

        jPanelControlVentana.add(jPanelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 5, 60, 25));

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("CONTROL REMOTO DEL CAMPAMENTO");
        jPanelControlVentana.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, 20));

        jPanelDatos.setBackground(new java.awt.Color(0, 0, 0));
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelActividades1.setBackground(new java.awt.Color(39, 43, 51));
        jPanelActividades1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelActividades1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelActividades1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("SOGA");
        jPanelActividades1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 40));

        jPanelDatos.add(jPanelActividades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 270, 150));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanelDatos.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 10, 610));

        jPanelActividades2.setBackground(new java.awt.Color(39, 43, 51));
        jPanelActividades2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelActividades2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelActividades2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("TIROLINA");
        jPanelActividades2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 40));

        jLabel42.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("Numero de usos:");
        jPanelActividades2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 90, 30));

        jLabelUsosTirolina.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jLabelUsosTirolina.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsosTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsosTirolina.setText("50");
        jPanelActividades2.add(jLabelUsosTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 30, 30));

        jLabel43.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Consultar cola de espera:");
        jPanelActividades2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, 20));

        jLabelColaEsperaTirolina.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jLabelColaEsperaTirolina.setForeground(new java.awt.Color(255, 255, 255));
        jLabelColaEsperaTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColaEsperaTirolina.setText("0");
        jPanelActividades2.add(jLabelColaEsperaTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 30, 20));

        jLabelLupaUsosTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLupaUsosTirolina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa20px.png"))); // NOI18N
        jPanelActividades2.add(jLabelLupaUsosTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, 40));

        jLabelLupaColaEsperaTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLupaColaEsperaTirolina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa20px.png"))); // NOI18N
        jPanelActividades2.add(jLabelLupaColaEsperaTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, 40));

        jPanelDatos.add(jPanelActividades2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 150));

        javax.swing.GroupLayout jPanelVentanaLayout = new javax.swing.GroupLayout(jPanelVentana);
        jPanelVentana.setLayout(jPanelVentanaLayout);
        jPanelVentanaLayout.setHorizontalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelControlVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanelVentanaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelVentanaLayout.setVerticalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentanaLayout.createSequentialGroup()
                .addComponent(jPanelControlVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(255,106,105));
        jLabelCerrar.setForeground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(39,43,51));
        jLabelCerrar.setForeground( new Color(255,106,105));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelControlVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControlVentanaMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanelControlVentanaMousePressed

    private void jPanelControlVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControlVentanaMouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanelControlVentanaMouseDragged

    private void jPanelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jPanelMinimizarMouseClicked

    private void jPanelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseEntered
        // TODO add your handling code here:
        jPanelMinimizar.setBackground( new Color(122,130,142));
    }//GEN-LAST:event_jPanelMinimizarMouseEntered

    private void jPanelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseExited
        // TODO add your handling code here:
        jPanelMinimizar.setBackground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelMinimizarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente interfaz = new Cliente();
                interfaz.setLocationRelativeTo(null);
                interfaz.setVisible(true);
                interfaz.x = interfaz.getX();
                interfaz.y = interfaz.getY();            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelColaEsperaTirolina;
    private javax.swing.JLabel jLabelLupaColaEsperaTirolina;
    private javax.swing.JLabel jLabelLupaUsosTirolina;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelUsosTirolina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelActividades1;
    private javax.swing.JPanel jPanelActividades2;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelControlVentana;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelEspaciado;
    private javax.swing.JPanel jPanelMinimizar;
    private javax.swing.JPanel jPanelVentana;
    // End of variables declaration//GEN-END:variables
}
