/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RMI;

import Servidor.InterfaceCampamento;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Edu
 */
public class ClienteRMI extends javax.swing.JFrame {

    private int x,y;
    
    public ClienteRMI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentana = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelNiño = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelActividadesTotales = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelLupaInfoNiño = new javax.swing.JLabel();
        jPanelTirolina = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelColaTirolina = new javax.swing.JLabel();
        jLabelUsosTirolina = new javax.swing.JLabel();
        jLabelLupaInfoNiño1 = new javax.swing.JLabel();
        jLabelLupaInfoNiño2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanelSoga = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelNiñosSoga = new javax.swing.JLabel();
        jLabelLupaInfoNiño4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelMerendero = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelBandejasLimpiasMerendero = new javax.swing.JLabel();
        jLabelBandejasSuciasMerendero = new javax.swing.JLabel();
        jLabelNiñosMerendero = new javax.swing.JLabel();
        jLabelLupaInfoNiño3 = new javax.swing.JLabel();
        jLabelLupaInfoNiño5 = new javax.swing.JLabel();
        jLabelLupaInfoNiño6 = new javax.swing.JLabel();
        jPanelControlVentana = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelEspaciado = new javax.swing.JPanel();
        jPanelMinimizar = new javax.swing.JPanel();
        jLabelMinimizar = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelVentana.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentana.setPreferredSize(new java.awt.Dimension(470, 350));
        jPanelVentana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNiño.setBackground(new java.awt.Color(39, 43, 51));
        jPanelNiño.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Introduce el identificador de un niño:");
        jPanelNiño.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 210, -1));

        jTextField7.setFocusable(false);
        jPanelNiño.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 60, 20));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("INFORMACIÓN NIÑO");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jPanelNiño.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 30));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Actividades totales:");
        jPanelNiño.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 120, -1));

        jLabelActividadesTotales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelActividadesTotales.setText("...");
        jPanelNiño.add(jLabelActividadesTotales, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 60, -1));
        jPanelNiño.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabelLupaInfoNiño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLupaInfoNiño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa20px_1.png"))); // NOI18N
        jLabelLupaInfoNiño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiñoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiñoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiñoMouseExited(evt);
            }
        });
        jPanelNiño.add(jLabelLupaInfoNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, 24, 30));

        jPanel1.add(jPanelNiño, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 70));

        jPanelTirolina.setBackground(new java.awt.Color(39, 43, 51));
        jPanelTirolina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Cola de espera:");
        jPanelTirolina.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 120, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Numero de usos:");
        jPanelTirolina.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 120, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TIROLINA");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jPanelTirolina.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 30));

        jLabelColaTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColaTirolina.setText("...");
        jPanelTirolina.add(jLabelColaTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 60, -1));

        jLabelUsosTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsosTirolina.setText("...");
        jPanelTirolina.add(jLabelUsosTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 60, -1));

        jLabelLupaInfoNiño1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLupaInfoNiño1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa20px_1.png"))); // NOI18N
        jLabelLupaInfoNiño1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño1MouseExited(evt);
            }
        });
        jPanelTirolina.add(jLabelLupaInfoNiño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, 24, 30));

        jLabelLupaInfoNiño2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLupaInfoNiño2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa20px_1.png"))); // NOI18N
        jLabelLupaInfoNiño2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño2MouseExited(evt);
            }
        });
        jPanelTirolina.add(jLabelLupaInfoNiño2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 65, 24, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Tirolina (1) (2).png"))); // NOI18N
        jPanelTirolina.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 30));

        jPanel1.add(jPanelTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 320, 100));

        jPanelSoga.setBackground(new java.awt.Color(39, 43, 51));
        jPanelSoga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Niños en soga:");
        jPanelSoga.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 130, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SOGA");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jPanelSoga.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 30));

        jLabelNiñosSoga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNiñosSoga.setText("...");
        jPanelSoga.add(jLabelNiñosSoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 60, -1));

        jLabelLupaInfoNiño4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLupaInfoNiño4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa20px_1.png"))); // NOI18N
        jLabelLupaInfoNiño4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño4MouseExited(evt);
            }
        });
        jPanelSoga.add(jLabelLupaInfoNiño4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 24, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Soga (1) (1).png"))); // NOI18N
        jPanelSoga.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 30));

        jPanel1.add(jPanelSoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 320, 100));

        jPanelMerendero.setBackground(new java.awt.Color(39, 43, 51));
        jPanelMerendero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Merendero (1) (1).png"))); // NOI18N
        jPanelMerendero.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Bandejas limpias:");
        jPanelMerendero.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 130, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Bandejas sucias:");
        jPanelMerendero.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 120, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Niños en el merendero: ");
        jPanelMerendero.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("MERENDERO");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));
        jPanelMerendero.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanelMerendero.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 20, 30));

        jLabelBandejasLimpiasMerendero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBandejasLimpiasMerendero.setText("...");
        jPanelMerendero.add(jLabelBandejasLimpiasMerendero, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 60, -1));

        jLabelBandejasSuciasMerendero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBandejasSuciasMerendero.setText("...");
        jPanelMerendero.add(jLabelBandejasSuciasMerendero, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 60, -1));

        jLabelNiñosMerendero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNiñosMerendero.setText("...");
        jPanelMerendero.add(jLabelNiñosMerendero, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 60, -1));

        jLabelLupaInfoNiño3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLupaInfoNiño3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa20px_1.png"))); // NOI18N
        jLabelLupaInfoNiño3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño3MouseExited(evt);
            }
        });
        jPanelMerendero.add(jLabelLupaInfoNiño3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 30));

        jLabelLupaInfoNiño5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLupaInfoNiño5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa20px_1.png"))); // NOI18N
        jLabelLupaInfoNiño5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño5MouseExited(evt);
            }
        });
        jPanelMerendero.add(jLabelLupaInfoNiño5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 35, 24, 30));

        jLabelLupaInfoNiño6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLupaInfoNiño6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa20px_1.png"))); // NOI18N
        jLabelLupaInfoNiño6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLupaInfoNiño6MouseExited(evt);
            }
        });
        jPanelMerendero.add(jLabelLupaInfoNiño6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 65, 24, 30));

        jPanel1.add(jPanelMerendero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 650, 100));

        jPanelVentana.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 46, 670, 310));

        jPanelControlVentana.setBackground(new java.awt.Color(39, 43, 51));
        jPanelControlVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelControlVentanaMouseDragged(evt);
            }
        });
        jPanelControlVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelControlVentanaMousePressed(evt);
            }
        });
        jPanelControlVentana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(39, 43, 51));
        jPanelCerrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setFont(new java.awt.Font("Roboto Light", 0, 28)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jPanelCerrar.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 15));

        jPanelControlVentana.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 60, 25));

        jPanelEspaciado.setBackground(new java.awt.Color(39, 43, 51));

        javax.swing.GroupLayout jPanelEspaciadoLayout = new javax.swing.GroupLayout(jPanelEspaciado);
        jPanelEspaciado.setLayout(jPanelEspaciadoLayout);
        jPanelEspaciadoLayout.setHorizontalGroup(
            jPanelEspaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanelEspaciadoLayout.setVerticalGroup(
            jPanelEspaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelControlVentana.add(jPanelEspaciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, 40));

        jPanelMinimizar.setBackground(new java.awt.Color(39, 43, 51));
        jPanelMinimizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelMinimizar.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseExited(evt);
            }
        });
        jPanelMinimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMinimizar.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLabelMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar.setText("_");
        jPanelMinimizar.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        jPanelControlVentana.add(jPanelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 60, 25));

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("CONTROL REMOTO DEL CAMPAMENTO");
        jPanelControlVentana.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 490, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Campamento (1) (1).png"))); // NOI18N
        jPanelControlVentana.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 30));

        jPanelVentana.add(jPanelControlVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 670, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(255,106,105));
        jLabelCerrar.setForeground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(39,43,51));
        jLabelCerrar.setForeground( new Color(255,106,105));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jPanelMinimizarMouseClicked

    private void jPanelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseEntered
        // TODO add your handling code here:
        jPanelMinimizar.setBackground( new Color(122,130,142));
    }//GEN-LAST:event_jPanelMinimizarMouseEntered

    private void jPanelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseExited
        // TODO add your handling code here:
        jPanelMinimizar.setBackground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelMinimizarMouseExited

    private void jPanelControlVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControlVentanaMouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanelControlVentanaMouseDragged

    private void jPanelControlVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControlVentanaMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanelControlVentanaMousePressed

    private void jLabelLupaInfoNiñoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiñoMouseClicked
        // TODO add your handling code here:
        String id=jTextField7.getText();
        try {
            InterfaceCampamento metodos = (InterfaceCampamento) Naming.lookup("//localhost/ObjetoSaluda");  
            String actividades = metodos.actividadesNiño(id);
            jLabelActividadesTotales.setText(actividades);
        }
        catch (Exception e) 
        {
            System.out.println("Excepción : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabelLupaInfoNiñoMouseClicked

    private void jLabelLupaInfoNiñoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiñoMouseEntered
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    }//GEN-LAST:event_jLabelLupaInfoNiñoMouseEntered

    private void jLabelLupaInfoNiñoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiñoMouseExited
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }//GEN-LAST:event_jLabelLupaInfoNiñoMouseExited

    private void jLabelLupaInfoNiño1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño1MouseClicked
        // TODO add your handling code here:
        try{
            InterfaceCampamento metodos = (InterfaceCampamento) Naming.lookup("//localhost/ObjetoSaluda"); 
            String contT="";
            contT = metodos.niñosenColaTirolina();
            jLabelColaTirolina.setText(contT);
        }
        catch (Exception e) 
        {
            System.out.println("Excepción : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabelLupaInfoNiño1MouseClicked

    private void jLabelLupaInfoNiño1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño1MouseEntered
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    }//GEN-LAST:event_jLabelLupaInfoNiño1MouseEntered

    private void jLabelLupaInfoNiño1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño1MouseExited
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }//GEN-LAST:event_jLabelLupaInfoNiño1MouseExited

    private void jLabelLupaInfoNiño2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño2MouseClicked
        // TODO add your handling code here:
        try{
            InterfaceCampamento metodos = (InterfaceCampamento) Naming.lookup("//localhost/ObjetoSaluda"); 
            String veces="";
            veces = metodos.vecesTirolina();
            jLabelUsosTirolina.setText(veces);
        }
        catch (Exception e) 
        {
            System.out.println("Excepción : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabelLupaInfoNiño2MouseClicked

    private void jLabelLupaInfoNiño2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño2MouseEntered
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    }//GEN-LAST:event_jLabelLupaInfoNiño2MouseEntered

    private void jLabelLupaInfoNiño2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño2MouseExited
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }//GEN-LAST:event_jLabelLupaInfoNiño2MouseExited

    private void jLabelLupaInfoNiño3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño3MouseClicked
        // TODO add your handling code here:
        try{
            InterfaceCampamento metodos = (InterfaceCampamento) Naming.lookup("//localhost/ObjetoSaluda"); 
            String contM="";
            contM = metodos.niñosenMerienda();
            jLabelNiñosMerendero.setText(contM);
        }
        catch (Exception e) 
        {
            System.out.println("Excepción : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabelLupaInfoNiño3MouseClicked

    private void jLabelLupaInfoNiño3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño3MouseEntered
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    }//GEN-LAST:event_jLabelLupaInfoNiño3MouseEntered

    private void jLabelLupaInfoNiño3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño3MouseExited
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }//GEN-LAST:event_jLabelLupaInfoNiño3MouseExited

    private void jLabelLupaInfoNiño4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño4MouseClicked
        // TODO add your handling code here:
        try{
            InterfaceCampamento metodos = (InterfaceCampamento) Naming.lookup("//localhost/ObjetoSaluda"); 
            String contS="";
            contS = metodos.niñosenColaSoga();
            jLabelNiñosSoga.setText(contS);
        }
        catch (Exception e) 
        {
            System.out.println("Excepción : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabelLupaInfoNiño4MouseClicked

    private void jLabelLupaInfoNiño4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño4MouseEntered
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    }//GEN-LAST:event_jLabelLupaInfoNiño4MouseEntered

    private void jLabelLupaInfoNiño4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño4MouseExited
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }//GEN-LAST:event_jLabelLupaInfoNiño4MouseExited

    private void jLabelLupaInfoNiño5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño5MouseClicked
        // TODO add your handling code here:
        try{
            InterfaceCampamento metodos = (InterfaceCampamento) Naming.lookup("//localhost/ObjetoSaluda"); 
            String BLimpias="";
            BLimpias = metodos.bandejasLimpiasMerienda();
            jLabelBandejasLimpiasMerendero.setText(BLimpias);
        }
        catch (Exception e) 
        {
            System.out.println("Excepción : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabelLupaInfoNiño5MouseClicked

    private void jLabelLupaInfoNiño5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño5MouseEntered
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    }//GEN-LAST:event_jLabelLupaInfoNiño5MouseEntered

    private void jLabelLupaInfoNiño5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño5MouseExited
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }//GEN-LAST:event_jLabelLupaInfoNiño5MouseExited

    private void jLabelLupaInfoNiño6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño6MouseClicked
        // TODO add your handling code here:
        try{
            InterfaceCampamento metodos = (InterfaceCampamento) Naming.lookup("//localhost/ObjetoSaluda");  
            String BSucias="";
            BSucias = metodos.bandejasSuciasMerienda();
            jLabelBandejasSuciasMerendero.setText(BSucias);
        }
        catch (Exception e) 
        {
            System.out.println("Excepción : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLabelLupaInfoNiño6MouseClicked

    private void jLabelLupaInfoNiño6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño6MouseEntered
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
    }//GEN-LAST:event_jLabelLupaInfoNiño6MouseEntered

    private void jLabelLupaInfoNiño6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLupaInfoNiño6MouseExited
        // TODO add your handling code here:
        jLabelLupaInfoNiño.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
    }//GEN-LAST:event_jLabelLupaInfoNiño6MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClienteRMI interfaz = new ClienteRMI();
                interfaz.setLocationRelativeTo(null);
                interfaz.setVisible(true);
                interfaz.x = interfaz.getX();
                interfaz.y = interfaz.getY(); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelActividadesTotales;
    private javax.swing.JLabel jLabelBandejasLimpiasMerendero;
    private javax.swing.JLabel jLabelBandejasSuciasMerendero;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelColaTirolina;
    private javax.swing.JLabel jLabelLupaInfoNiño;
    private javax.swing.JLabel jLabelLupaInfoNiño1;
    private javax.swing.JLabel jLabelLupaInfoNiño2;
    private javax.swing.JLabel jLabelLupaInfoNiño3;
    private javax.swing.JLabel jLabelLupaInfoNiño4;
    private javax.swing.JLabel jLabelLupaInfoNiño5;
    private javax.swing.JLabel jLabelLupaInfoNiño6;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelNiñosMerendero;
    private javax.swing.JLabel jLabelNiñosSoga;
    private javax.swing.JLabel jLabelUsosTirolina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelControlVentana;
    private javax.swing.JPanel jPanelEspaciado;
    private javax.swing.JPanel jPanelMerendero;
    private javax.swing.JPanel jPanelMinimizar;
    private javax.swing.JPanel jPanelNiño;
    private javax.swing.JPanel jPanelSoga;
    private javax.swing.JPanel jPanelTirolina;
    private javax.swing.JPanel jPanelVentana;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
