/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RMI;

import Actividades.Merienda;
import Actividades.Soga;
import Actividades.Tirolina;
import Actividades.ZonaComun;
import Clases.Campamento;
import Entradas.EntradaNorte;
import Entradas.EntradaSur;
import ClasesAsociadasJFrame.ListaMonitores;
import ClasesAsociadasJFrame.ListaNiños;
import ClasesAsociadasJFrame.Plazas;
import PararReanudar.Paso;
import Threads.Monitor;
import Threads.Niño;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import static java.lang.Thread.sleep;
import java.rmi.Naming;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Francisco
 */
public class Servidor extends javax.swing.JFrame {

    /**
     * Creates new form Servidor
     */
    private int x, y;
    private Paso paso;
    
    public Servidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVentana = new javax.swing.JPanel();
        jPanelControlVentana = new javax.swing.JPanel();
        jPanelCerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanelStop = new javax.swing.JPanel();
        jLabelStop = new javax.swing.JLabel();
        jPanelEspaciado = new javax.swing.JPanel();
        jPanelMinimizar = new javax.swing.JPanel();
        jLabelMinimizar = new javax.swing.JLabel();
        jPanelRunnear = new javax.swing.JPanel();
        jLabelRunnear = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jPanelEntradaNorte = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabelNiñosZonaComun = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabelMonitoresZonaComun = new javax.swing.JLabel();
        jPanelEntradaSur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabelEntradaSur = new javax.swing.JLabel();
        jPanelActividades1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanelEntradaNorte4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabelNiñosComiendoMerienda = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabelColaMerienda = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabelBandejasLimpiasMerienda = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabelBandejasSuciasMerienda = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabelMonitoresMerienda = new javax.swing.JLabel();
        jPanelEntradaNorte5 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabelColaSoga = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabelMonitorSoga = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabelEquipo1Soga = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabelEquipo2Soga = new javax.swing.JLabel();
        jPanelEntradaNorte6 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabelFinalizacionTirolina = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabelColaTirolina = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jLabelTirolina = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabelPreparacionTirolina = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabelMonitorTirolina = new javax.swing.JLabel();
        jPanelEntradaNorte1 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabelEntradaNorte = new javax.swing.JLabel();
        jPanelEntradaNorte2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelPlazasDisponibles = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabelPlazasOcupadas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelVentana.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentana.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jPanelControlVentana.setBackground(new java.awt.Color(39, 43, 51));
        jPanelControlVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelControlVentanaMouseDragged(evt);
            }
        });
        jPanelControlVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelControlVentanaMousePressed(evt);
            }
        });
        jPanelControlVentana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCerrar.setBackground(new java.awt.Color(39, 43, 51));
        jPanelCerrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCerrarMouseExited(evt);
            }
        });
        jPanelCerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setFont(new java.awt.Font("Roboto Light", 0, 28)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("X");
        jPanelCerrar.add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 40, 15));

        jPanelControlVentana.add(jPanelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 5, 60, 25));

        jPanelStop.setBackground(new java.awt.Color(39, 43, 51));
        jPanelStop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelStop.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanelStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelStopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelStopMouseExited(evt);
            }
        });
        jPanelStop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelStop.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabelStop.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStop.setText("STOP");
        jPanelStop.add(jLabelStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 25));

        jPanelControlVentana.add(jPanelStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 5, 120, 25));

        jPanelEspaciado.setBackground(new java.awt.Color(39, 43, 51));

        javax.swing.GroupLayout jPanelEspaciadoLayout = new javax.swing.GroupLayout(jPanelEspaciado);
        jPanelEspaciado.setLayout(jPanelEspaciadoLayout);
        jPanelEspaciadoLayout.setHorizontalGroup(
            jPanelEspaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanelEspaciadoLayout.setVerticalGroup(
            jPanelEspaciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanelControlVentana.add(jPanelEspaciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, 40));

        jPanelMinimizar.setBackground(new java.awt.Color(39, 43, 51));
        jPanelMinimizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelMinimizar.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanelMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelMinimizarMouseExited(evt);
            }
        });
        jPanelMinimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMinimizar.setFont(new java.awt.Font("Magneto", 0, 18)); // NOI18N
        jLabelMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinimizar.setText("_");
        jPanelMinimizar.add(jLabelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        jPanelControlVentana.add(jPanelMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 5, 60, 25));

        jPanelRunnear.setBackground(new java.awt.Color(39, 43, 51));
        jPanelRunnear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanelRunnear.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanelRunnear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRunnearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelRunnearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelRunnearMouseExited(evt);
            }
        });
        jPanelRunnear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRunnear.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabelRunnear.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRunnear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRunnear.setText("RUN");
        jPanelRunnear.add(jLabelRunnear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 25));

        jPanelControlVentana.add(jPanelRunnear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 60, 25));

        jPanelDatos.setBackground(new java.awt.Color(0, 0, 0));
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelEntradaNorte.setBackground(new java.awt.Color(39, 43, 51));
        jPanelEntradaNorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelEntradaNorte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ZONA COMÚN");
        jPanelEntradaNorte.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 30));

        jLabel46.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Niños");
        jPanelEntradaNorte.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 790, 30));

        jLabel47.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Monitores");
        jPanelEntradaNorte.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 30));

        jPanel19.setBackground(new java.awt.Color(0, 0, 0));
        jPanel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel19.setForeground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNiñosZonaComun.setForeground(new java.awt.Color(255, 255, 255));
        jPanel19.add(jLabelNiñosZonaComun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, 10));

        jPanelEntradaNorte.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 790, 30));

        jPanel20.setBackground(new java.awt.Color(0, 0, 0));
        jPanel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMonitoresZonaComun.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonitoresZonaComun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel20.add(jLabelMonitoresZonaComun, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 10));

        jPanelEntradaNorte.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 30));

        jPanelDatos.add(jPanelEntradaNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1050, 110));

        jPanelEntradaSur.setBackground(new java.awt.Color(39, 43, 51));
        jPanelEntradaSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelEntradaSur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRADA SUR");
        jPanelEntradaSur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        jPanel22.setBackground(new java.awt.Color(0, 0, 0));
        jPanel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel22.setForeground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEntradaSur.setForeground(new java.awt.Color(255, 255, 255));
        jPanel22.add(jLabelEntradaSur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 10));

        jPanelEntradaSur.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 30));

        jPanelDatos.add(jPanelEntradaSur, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 450, 80));

        jPanelActividades1.setBackground(new java.awt.Color(39, 43, 51));
        jPanelActividades1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelActividades1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelActividades1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("ACTIVIDADES");
        jPanelActividades1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 40));

        jPanelEntradaNorte4.setBackground(new java.awt.Color(39, 43, 51));
        jPanelEntradaNorte4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelEntradaNorte4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Niños Comiendo");
        jPanelEntradaNorte4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 610, 30));

        jLabel26.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("MERENDERO");
        jPanelEntradaNorte4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1010, 40));

        jLabel27.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Cola");
        jPanelEntradaNorte4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 30));

        jLabel28.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Monitores");
        jPanelEntradaNorte4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, 30));

        jLabel29.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Bandejas Limpias");
        jPanelEntradaNorte4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 100, 30));

        jLabel30.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Bandejas Sucias");
        jPanelEntradaNorte4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, 30));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNiñosComiendoMerienda.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jLabelNiñosComiendoMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 10));

        jPanelEntradaNorte4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 610, 30));

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));
        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelColaMerienda.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.add(jLabelColaMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 10));

        jPanelEntradaNorte4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 950, 30));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel12.setForeground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBandejasLimpiasMerienda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBandejasLimpiasMerienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(jLabelBandejasLimpiasMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 10));

        jPanelEntradaNorte4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 80, 30));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBandejasSuciasMerienda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBandejasSuciasMerienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(jLabelBandejasSuciasMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 10));

        jPanelEntradaNorte4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 80, 30));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMonitoresMerienda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonitoresMerienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(jLabelMonitoresMerienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 10));

        jPanelEntradaNorte4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 30));

        jPanelActividades1.add(jPanelEntradaNorte4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 1030, 150));

        jPanelEntradaNorte5.setBackground(new java.awt.Color(39, 43, 51));
        jPanelEntradaNorte5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelEntradaNorte5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("SOGA");
        jPanelEntradaNorte5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, 40));

        jLabel37.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Cola");
        jPanelEntradaNorte5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 30));

        jLabel38.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Monitor");
        jPanelEntradaNorte5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 30));

        jLabel39.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Equipo 2");
        jPanelEntradaNorte5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 180, 30));

        jLabel40.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Equipo 1");
        jPanelEntradaNorte5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, 30));

        jPanel15.setBackground(new java.awt.Color(0, 0, 0));
        jPanel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelColaSoga.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.add(jLabelColaSoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 10));

        jPanelEntradaNorte5.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 430, 30));

        jPanel16.setBackground(new java.awt.Color(0, 0, 0));
        jPanel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMonitorSoga.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonitorSoga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel16.add(jLabelMonitorSoga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 10));

        jPanelEntradaNorte5.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 30));

        jPanel17.setBackground(new java.awt.Color(0, 0, 0));
        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel17.setForeground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEquipo1Soga.setForeground(new java.awt.Color(255, 255, 255));
        jPanel17.add(jLabelEquipo1Soga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 10));

        jPanelEntradaNorte5.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 30));

        jPanel18.setBackground(new java.awt.Color(0, 0, 0));
        jPanel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEquipo2Soga.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.add(jLabelEquipo2Soga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 10));

        jPanelEntradaNorte5.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 180, 30));

        jPanelActividades1.add(jPanelEntradaNorte5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 510, 160));

        jPanelEntradaNorte6.setBackground(new java.awt.Color(39, 43, 51));
        jPanelEntradaNorte6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelEntradaNorte6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Finalizacion");
        jPanelEntradaNorte6.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 80, 30));

        jLabel53.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("TIROLINA");
        jPanelEntradaNorte6.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, 40));

        jLabel54.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Cola");
        jPanelEntradaNorte6.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 30));

        jLabel55.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Monitor");
        jPanelEntradaNorte6.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 30));

        jLabel56.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Tirolina");
        jPanelEntradaNorte6.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 80, 30));

        jLabel57.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Preparación");
        jPanelEntradaNorte6.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 80, 30));

        jPanel23.setBackground(new java.awt.Color(0, 0, 0));
        jPanel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel23.setForeground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFinalizacionTirolina.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFinalizacionTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel23.add(jLabelFinalizacionTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 10));

        jPanelEntradaNorte6.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 80, 30));

        jPanel24.setBackground(new java.awt.Color(0, 0, 0));
        jPanel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel24.setForeground(new java.awt.Color(255, 255, 255));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelColaTirolina.setForeground(new java.awt.Color(255, 255, 255));
        jPanel24.add(jLabelColaTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 10));

        jPanelEntradaNorte6.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 430, 30));

        jPanel25.setBackground(new java.awt.Color(0, 0, 0));
        jPanel25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel25.setForeground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTirolina.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel25.add(jLabelTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 10));

        jPanelEntradaNorte6.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 80, 30));

        jPanel26.setBackground(new java.awt.Color(0, 0, 0));
        jPanel26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel26.setForeground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPreparacionTirolina.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPreparacionTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel26.add(jLabelPreparacionTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 10));

        jPanelEntradaNorte6.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 80, 30));

        jPanel27.setBackground(new java.awt.Color(0, 0, 0));
        jPanel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel27.setForeground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMonitorTirolina.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMonitorTirolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel27.add(jLabelMonitorTirolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 10));

        jPanelEntradaNorte6.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        jPanelActividades1.add(jPanelEntradaNorte6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 510, 160));

        jPanelDatos.add(jPanelActividades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 1050, 390));

        jPanelEntradaNorte1.setBackground(new java.awt.Color(39, 43, 51));
        jPanelEntradaNorte1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelEntradaNorte1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("ENTRADA NORTE");
        jPanelEntradaNorte1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 40));

        jPanel21.setBackground(new java.awt.Color(0, 0, 0));
        jPanel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 130, 142), 1, true));
        jPanel21.setForeground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEntradaNorte.setForeground(new java.awt.Color(255, 255, 255));
        jPanel21.add(jLabelEntradaNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 10));

        jPanelEntradaNorte1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 30));

        jPanelDatos.add(jPanelEntradaNorte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 80));

        jPanelEntradaNorte2.setBackground(new java.awt.Color(39, 43, 51));
        jPanelEntradaNorte2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 130, 142)));
        jPanelEntradaNorte2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CAMPAMENTO");
        jPanelEntradaNorte2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 130, 10));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INFORMACIÓN");
        jPanelEntradaNorte2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        jLabelPlazasDisponibles.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jLabelPlazasDisponibles.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlazasDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlazasDisponibles.setText("50");
        jPanelEntradaNorte2.add(jLabelPlazasDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 30, 30));

        jLabel42.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("Plazas Disponibles:");
        jPanelEntradaNorte2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));

        jLabel43.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Plazas Ocupadas:");
        jPanelEntradaNorte2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 20));

        jLabelPlazasOcupadas.setFont(new java.awt.Font("Roboto Medium", 0, 10)); // NOI18N
        jLabelPlazasOcupadas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlazasOcupadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlazasOcupadas.setText("0");
        jPanelEntradaNorte2.add(jLabelPlazasOcupadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 30, 20));

        jPanelDatos.add(jPanelEntradaNorte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 130, 80));

        javax.swing.GroupLayout jPanelVentanaLayout = new javax.swing.GroupLayout(jPanelVentana);
        jPanelVentana.setLayout(jPanelVentanaLayout);
        jPanelVentanaLayout.setHorizontalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelControlVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelVentanaLayout.setVerticalGroup(
            jPanelVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentanaLayout.createSequentialGroup()
                .addComponent(jPanelControlVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanelCerrarMouseClicked

    private void jPanelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseEntered
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(255,106,105));
        jLabelCerrar.setForeground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelCerrarMouseEntered

    private void jPanelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCerrarMouseExited
        // TODO add your handling code here:
        jPanelCerrar.setBackground( new Color(39,43,51));
        jLabelCerrar.setForeground( new Color(255,106,105));
    }//GEN-LAST:event_jPanelCerrarMouseExited

    private void jPanelControlVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControlVentanaMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanelControlVentanaMousePressed

    private void jPanelControlVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelControlVentanaMouseDragged
        // TODO add your handling code here:
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPanelControlVentanaMouseDragged

    private void jPanelStopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStopMouseEntered
        // TODO add your handling code here:
        jPanelStop.setBackground( new Color(122,130,142));
    }//GEN-LAST:event_jPanelStopMouseEntered

    private void jPanelStopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStopMouseExited
        // TODO add your handling code here:
        jPanelStop.setBackground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelStopMouseExited

    private void jPanelStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStopMouseClicked
        // TODO add your handling code here:
        if(jLabelStop.getText() == "STOP")
        {
            jLabelStop.setText("REANUDAR");
            paso.cerrar();
        }
        else
        {
            jLabelStop.setText("STOP");
            paso.abrir();
        }
    }//GEN-LAST:event_jPanelStopMouseClicked

    private void jPanelMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jPanelMinimizarMouseClicked

    private void jPanelMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseEntered
        // TODO add your handling code here:
        jPanelMinimizar.setBackground( new Color(122,130,142));
    }//GEN-LAST:event_jPanelMinimizarMouseEntered

    private void jPanelMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMinimizarMouseExited
        // TODO add your handling code here:
        jPanelMinimizar.setBackground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelMinimizarMouseExited

    private void jPanelRunnearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRunnearMouseClicked
        // TODO add your handling code here
        
        //Boton Stop
        Paso paso = new Paso();
        this.paso = paso;
                
        Thread anonymousThread = new Thread(){ 	//Creating an object of Anonymous class which extends Thread class and passing this object to the reference of Thread class.
            public void run()	//Anonymous class overriding run() method of Thread class
            {
                
                //Plazas
                Plazas plazas = new Plazas(jLabelPlazasOcupadas, jLabelPlazasDisponibles);

                //Merienda
                ListaMonitores monitoresMerienda = new ListaMonitores(jLabelMonitoresMerienda);
                ListaNiños colaMerienda = new ListaNiños(jLabelColaMerienda);
                ListaNiños comiendoMerienda = new ListaNiños(jLabelNiñosComiendoMerienda);
                Merienda merienda = new Merienda(monitoresMerienda, colaMerienda, comiendoMerienda, jLabelBandejasSuciasMerienda, jLabelBandejasLimpiasMerienda, paso);

                //Soga
                ListaNiños colaSoga = new ListaNiños(jLabelColaSoga);
                ListaNiños equipo1Soga = new ListaNiños(jLabelEquipo1Soga);
                ListaNiños equipo2Soga = new ListaNiños(jLabelEquipo2Soga);
                ListaMonitores monitorSoga = new ListaMonitores(jLabelMonitorSoga);
                Soga soga = new Soga(monitorSoga, colaSoga, equipo1Soga, equipo2Soga, paso);

                //Tirolina
                ListaMonitores monitorTirolina = new ListaMonitores(jLabelMonitorTirolina);
                ListaNiños colaTirolina = new ListaNiños(jLabelColaTirolina);
                ListaNiños preparacionTirolina = new ListaNiños(jLabelPreparacionTirolina);
                ListaNiños entirolina = new ListaNiños(jLabelTirolina);
                ListaNiños finalizacionTirolina = new ListaNiños(jLabelFinalizacionTirolina);     
                Tirolina tirolina = new Tirolina(monitorTirolina, colaTirolina, preparacionTirolina, entirolina, finalizacionTirolina, paso);

                //Lock explícito y condicion
                Lock cerrojo = new ReentrantLock();
                Condition norte = cerrojo.newCondition();
                Condition sur = cerrojo.newCondition();

                //Zona Comun, Niños y monitores entran primero a la zona comun, y salen desde la zona comun
                ListaNiños colaNorte = new ListaNiños(jLabelEntradaNorte);
                ListaNiños colaSur = new ListaNiños(jLabelEntradaSur);
                ListaMonitores monitoresZonaComun = new ListaMonitores(jLabelMonitoresZonaComun);
                ListaNiños niñosZonaComun = new ListaNiños(jLabelNiñosZonaComun);  
                ZonaComun zonaComun = new ZonaComun(monitoresZonaComun, niñosZonaComun, norte, sur, colaNorte, colaSur, merienda, soga, tirolina, plazas, paso);

                //EntradaNorte 
                EntradaNorte entradaNorte = new EntradaNorte(plazas, colaNorte, zonaComun, cerrojo, norte);

                //EntradaSur 
                EntradaSur entradaSur = new EntradaSur(plazas, colaSur, zonaComun, cerrojo, norte);

                //Campamento
                Campamento campamento = new Campamento(merienda, soga, tirolina, zonaComun, entradaNorte, entradaSur, plazas);

                //AlternanciaMonitoresEntrada
                AtomicInteger alternanciaMonitores = new AtomicInteger(0);

                for (int m = 1; m <= 4; m++)
                {
                    paso.mirar();
                    Monitor monitor = new Monitor(m, campamento, entradaNorte, entradaSur, alternanciaMonitores,zonaComun,soga,tirolina,merienda, paso);
                    monitor.start();
                }
                
                for (int n = 1; n <=2000; n++)
                {
                    paso.mirar();
                    Niño niño = new Niño(n, campamento, entradaNorte, entradaSur,zonaComun,merienda,tirolina,soga, paso);
                    //anonimus runnable
                    niño.start();
                    paso.mirar();
                    try
                    {
                        sleep(2000);
                    }
                    catch(InterruptedException e){}
                }    
            }
	};
        anonymousThread.start();
    }//GEN-LAST:event_jPanelRunnearMouseClicked

    private void jPanelRunnearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRunnearMouseEntered
        // TODO add your handling code here:
        jPanelRunnear.setBackground( new Color(122,130,142));
    }//GEN-LAST:event_jPanelRunnearMouseEntered

    private void jPanelRunnearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRunnearMouseExited
        // TODO add your handling code here:
        jPanelRunnear.setBackground( new Color(39,43,51));
    }//GEN-LAST:event_jPanelRunnearMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Servidor interfaz = new Servidor();
                interfaz.setLocationRelativeTo(null);
                interfaz.setVisible(true);
                interfaz.x = interfaz.getX();
                interfaz.y = interfaz.getY(); 
                
                //RMI
                /*
                try
                {
                    Metodos obj = new Metodos(); //Crea una instancia del objeto que implementa la interfaz, como objeto a registrar 
                    Registry registry = LocateRegistry.createRegistry(1099); //Arranca rmiregistry local en el puerto 1099
                    Naming.rebind("//localhost/ObjetoSaluda",obj);   //rebind sólo funciona sobre una url del equipo local 
                    System.out.println("El Objeto Saluda ha quedado registrado");
                }
                catch (Exception e)
                {
                    System.out.println(" Error: " + e.getMessage());
                    e.printStackTrace();
                }*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabelBandejasLimpiasMerienda;
    private javax.swing.JLabel jLabelBandejasSuciasMerienda;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelColaMerienda;
    private javax.swing.JLabel jLabelColaSoga;
    private javax.swing.JLabel jLabelColaTirolina;
    private javax.swing.JLabel jLabelEntradaNorte;
    private javax.swing.JLabel jLabelEntradaSur;
    private javax.swing.JLabel jLabelEquipo1Soga;
    private javax.swing.JLabel jLabelEquipo2Soga;
    private javax.swing.JLabel jLabelFinalizacionTirolina;
    private javax.swing.JLabel jLabelMinimizar;
    private javax.swing.JLabel jLabelMonitorSoga;
    private javax.swing.JLabel jLabelMonitorTirolina;
    private javax.swing.JLabel jLabelMonitoresMerienda;
    private javax.swing.JLabel jLabelMonitoresZonaComun;
    private javax.swing.JLabel jLabelNiñosComiendoMerienda;
    private javax.swing.JLabel jLabelNiñosZonaComun;
    private javax.swing.JLabel jLabelPlazasDisponibles;
    private javax.swing.JLabel jLabelPlazasOcupadas;
    private javax.swing.JLabel jLabelPreparacionTirolina;
    private javax.swing.JLabel jLabelRunnear;
    private javax.swing.JLabel jLabelStop;
    private javax.swing.JLabel jLabelTirolina;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanelActividades1;
    private javax.swing.JPanel jPanelCerrar;
    private javax.swing.JPanel jPanelControlVentana;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelEntradaNorte;
    private javax.swing.JPanel jPanelEntradaNorte1;
    private javax.swing.JPanel jPanelEntradaNorte2;
    private javax.swing.JPanel jPanelEntradaNorte4;
    private javax.swing.JPanel jPanelEntradaNorte5;
    private javax.swing.JPanel jPanelEntradaNorte6;
    private javax.swing.JPanel jPanelEntradaSur;
    private javax.swing.JPanel jPanelEspaciado;
    private javax.swing.JPanel jPanelMinimizar;
    private javax.swing.JPanel jPanelRunnear;
    private javax.swing.JPanel jPanelStop;
    private javax.swing.JPanel jPanelVentana;
    // End of variables declaration//GEN-END:variables
}
